
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_USERS_FETCH_REQUEST = 'ADMIN_USERS_FETCH_REQUEST';
export const ADMIN_USERS_FETCH_SUCCESS = 'ADMIN_USERS_FETCH_SUCCESS';
export const ADMIN_USERS_FETCH_FAILURE = 'ADMIN_USERS_FETCH_FAILURE';

export const ADMIN_USER_BLOCK_REQUEST = "ADMIN_USER_BLOCK_REQUEST";
export const ADMIN_USER_BLOCK_SUCCESS = " ADMIN_USER_BLOCK_SUCCESS";
export const ADMIN_USER_BLOCK_FAILURE = "ADMIN_USER_BLOCK_FAILURE";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAILURE = "ADMIN_USER_DELETE_FAILURE";

export const ADMIN_BOOK_ADD_REQUEST = "ADMIN_BOOK_ADD_REQUEST";
export const ADMIN_BOOK_ADD_SUCCESS = "ADMIN_BOOK_ADD_SUCCESS";
export const ADMIN_BOOK_ADD_FAILURE= "ADMIN_BOOK_ADD_FAILURE";

export const ADMIN_BOOK_FETCH_REQUEST ='ADMIN_BOOK_FETCH_REQUEST'
export const ADMIN_BOOK_FETCH_SUCCESS ='ADMIN_BOOK_FETCH_SUCCESS'
export const ADMIN_BOOK_FETCH_FAILURE ='ADMIN_BOOK_FETCH_FAILURE'


export const ADMIN_BOOK_DELETE_REQUEST ='ADMIN_BOOK_DELETE_REQUEST'
export const ADMIN_BOOK_DELETE_SUCCESS ='ADMIN_BOOK_DELETE_SUCCESS'
export const ADMIN_BOOK_DELETE_FAILURE ='ADMIN_BOOK_DELETE_FAILURE'

export const ADMIN_GET_LOCATION_REQUEST ='ADMIN_GET_LOCATION_REQUEST'
export const ADMIN_GET_LOCATION_SUCCESS = 'ADMIN_GET_LOCATION_SUCCESS'
export const ADMIN_GET_LOCATION_FAILURE = 'ADMIN_GET_LOCATION_FAILURE'

export const ADMIN_SEARCH_REQUEST = 'ADMIN_SEARCH_REQUEST'
export const ADMIN_SEARCH_SUCCESS = 'ADMIN_SEARCH_SUCCESS'
export const ADMIN_SEARCH_FAILURE = 'ADMIN_SEARCH_FAILURE'

export const ADMIN_ADD_GENRE_REQUEST = 'ADMIN_ADD_GENRE_REQUEST'
export const ADMIN_ADD_GENRE_SUCCESS = 'ADMIN_ADD_GENRE_SUCCESS'
export const ADMIN_ADD_GENRE_FAILURE = 'ADMIN_ADD_GENRE_FAILURE'

