
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_USERS_FETCH_REQUEST = 'ADMIN_USERS_FETCH_REQUEST';
export const ADMIN_USERS_FETCH_SUCCESS = 'ADMIN_USERS_FETCH_SUCCESS';
export const ADMIN_USERS_FETCH_FAILURE = 'ADMIN_USERS_FETCH_FAILURE';

export const ADMIN_USER_BLOCK_REQUEST = "ADMIN_USER_BLOCK_REQUEST";
export const ADMIN_USER_BLOCK_SUCCESS = " ADMIN_USER_BLOCK_SUCCESS";
export const ADMIN_USER_BLOCK_FAILURE = "ADMIN_USER_BLOCK_FAILURE";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAILURE = "ADMIN_USER_DELETE_FAILURE";