export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';


export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const UPLOAD_USER_IMAGE_REQUEST = 'UPLOAD_USER_IMAGE_REQUEST';
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS';
export const UPLOAD_USER_IMAGE_FAILURE = 'UPLOAD_USER_IMAGE_FAILURE';

export const USER_GET_BOOKS_REQUEST = 'USER_GET_BOOKS_REQUEST';
export const USER_GET_BOOKS_SUCCESS = 'USER_GET_BOOKS_SUCCESS';
export const USER_GET_BOOKS_FAILURE = 'USER_GET_BOOKS_FAILURE';

export const USER_GET_GENRE_BOOKS_REQUEST ='USER_GET_GENRE_BOOKS_REQUEST'
export const USER_GET_GENRE_BOOKS_SUCCESS ='USER_GET_GENRE_BOOKS_SUCCESS'
export const USER_GET_GENRE_BOOKS_FAILURE ='USER_GET_GENRE_BOOKS_FAILURE'
